#ifndef MILESTONES_H
#define MILESTONES_H

// Keep numbers here, helps identifying them and using in data/text/dialogue stuff

enum Milestone {
	MS_BATTLE_TUTORIAL_SELECT_ACTION = 0,
	MS_BATTLE_TUTORIAL_ATTACK_SELECT_TARGET = 1,
	MS_BATTLE_TUTORIAL_SELECT_ITEM = 2,
	MS_BATTLE_TUTORIAL_ITEM_SELECT_TARGET = 3,
	MS_BATTLE_TUTORIAL_SELECT_SPELL = 4,
	MS_BATTLE_TUTORIAL_SPELL_SELECT_TARGET = 5,
	MS_FIRST_SCENE = 6,
	MS_SWAPPED_TIGGY = 7,
	MS_LOOK_FOR_MORE = 8,
	MS_SAVEZONE_INTRO = 9,
	MS_FIRST_RANDOM_BATTLE = 10,
	MS_SECOND_RANDOM_BATTLE = 11,
	MS_RIVERSIDE_SOLDIER_CHAT = 12,
	MS_LEARNED_HEAL_FIRE = 13,
	MS_TALKED_TO_MAYOR = 14,
	MS_ENTERED_HAUNTED_HOUSE = 15,
	MS_FIRST_HH_RANDOM_BATTLE = 16,
	MS_FIRST_HH2_RANDOM_BATTLE = 17,
	MS_BEAT_PALLA = 18,
	MS_MAYOR_REPENTED = 19,
	MS_PALLA_LEFT = 20,
	MS_THIRD_BUTTON_HELP = 21,
	MS_TIGGY_HOO = 22,
	MS_BATTLE_TUTORIAL_SELECT_VAMPIRE = 23,
	MS_BATTLE_TUTORIAL_VAMPIRE_SELECT_TARGET = 24,
	MS_TALKED_ABOUT_BOATIN = 25,
	MS_ARRIVED_EAST = 26,
	MS_GOT_SCROLL_HELP = 27,
	MS_JUST_BEFORE_MONSTER = 28,
	MS_HOW_DID_WE_GET_HERE = 29,
	MS_GOT_HEAL_OMEGA = 30,
	MS_TALKED_TO_QUEEN = 31,
	MS_GETTING_CLOSE = 32,
	MS_PENDANTS_SCENE = 33,
	MS_CAN_USE_VFIRE = 34,
	MS_USED_VFIRE = 35,
	MS_PALLA_STEP = 36,
	MS_GAYAN_STEP = 37,
	MS_PALLA_STEP2 = 38,
	MS_GAYAN_STEP2 = 39,
	MS_SIZE
};

#endif // MILESTONES_H
